# Generated by Django 3.2.9 on 2021-11-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
