# Generated by Django 3.2.9 on 2021-11-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0002_socialmedia_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='iconClass',
            field=models.CharField(help_text='Eg: fa-linkedin', max_length=50),
        ),
    ]
