# Generated by Django 3.2.9 on 2021-11-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0003_alter_socialmedia_iconclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='iconClass',
            field=models.CharField(help_text='Eg: fa-linkedin', max_length=50, verbose_name='Font Awesom Icons'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='mediaURL',
            field=models.CharField(max_length=500, verbose_name='Social media URL'),
        ),
    ]
