# Generated by Django 3.2.9 on 2021-11-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0004_auto_20211105_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('High School', 'High School'), ('12th', '12th'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Others', 'Others')], max_length=50, verbose_name=' Choose level of academic')),
                ('course', models.CharField(max_length=100, verbose_name='Course Title')),
                ('college', models.CharField(max_length=250, verbose_name='College Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Explain about the course')),
                ('year_of_passing', models.IntegerField(verbose_name='Year of passing out')),
                ('is_active', models.BooleanField(default=True, verbose_name='ACtive Status')),
            ],
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ACtive Status'),
        ),
    ]
