# Generated by Django 3.2.9 on 2021-11-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0005_auto_20211106_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academics',
            options={'ordering': ['-year_of_passing']},
        ),
    ]
