# Generated by Django 3.2.9 on 2021-11-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0009_auto_20211106_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=100, verbose_name='Role Name')),
                ('company', models.CharField(max_length=250, verbose_name='Company Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Explain about the role')),
                ('from_year', models.DateField(verbose_name='Year of Joining')),
                ('to_year', models.DateField(null=True, verbose_name='Year of Resign')),
                ('is_active', models.BooleanField(default=True, verbose_name='ACtive Status')),
            ],
            options={
                'ordering': ['-to_year'],
            },
        ),
    ]
