# Generated by Django 3.2.9 on 2021-11-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0010_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='to_year',
            field=models.DateField(blank=True, null=True, verbose_name='Year of Resign'),
        ),
    ]
