# Generated by Django 3.2.9 on 2021-11-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0011_alter_professional_to_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'ordering': ['-from_year']},
        ),
    ]
