# Generated by Django 3.2.9 on 2021-11-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0012_alter_professional_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ACtive Status')),
                ('skill', models.CharField(max_length=75, verbose_name='Skill Name')),
                ('scale', models.IntegerField(default=50, help_text='Enter a range from 0 -100', verbose_name='Rating of skill')),
                ('is_key_skill', models.BooleanField(default=False, help_text='Check MArk if this is technical skill', verbose_name='Is this Tech Skill')),
            ],
            options={
                'ordering': ['-scale'],
            },
        ),
    ]
