# Generated by Django 3.2.9 on 2021-11-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0015_alter_skills_skillurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ACtive Status')),
                ('name', models.CharField(max_length=50, verbose_name='Profile Name')),
                ('desp', models.TextField(max_length=2000, verbose_name='About Me')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name=' Choose Sex')),
                ('age', models.IntegerField(default=18)),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Mobile Number')),
                ('location', models.CharField(max_length=100, verbose_name='Current Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
