# Generated by Django 3.2.9 on 2021-11-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0017_auto_20211107_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='bg'),
        ),
    ]
