# Generated by Django 3.2.9 on 2021-11-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0019_auto_20211109_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactProfile',
        ),
    ]
