# Generated by Django 3.2.9 on 2021-11-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0020_delete_contactprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomisedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('name', models.CharField(max_length=150, verbose_name='Template Name')),
                ('id_num', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
