# Generated by Django 3.2.9 on 2021-11-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0022_delete_customisedtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='bg',
        ),
        migrations.AlterField(
            model_name='about',
            name='avatar',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='URL to your Profile Pic'),
        ),
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='URL to your Resume'),
        ),
    ]
