# Generated by Django 3.2.9 on 2021-11-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0024_auto_20211112_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('name', models.CharField(max_length=50, verbose_name='Template Name')),
                ('id_num', models.IntegerField(verbose_name='Design Number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
